.TH "lenticular" "1" "https://github.com/amiaopensource/lenticular" "2018\-05\-26" "AMIA Open Source"
.SH NAME
\fBlenticular\fR \- Digital restoration of lenticular colours from greyscale digitisations
.SH SYNOPSIS
.SS
\fBlenticular
This is the main program for digital restoration of lenticular colours from greyscale digitisations. Currently only the TIFF \fIgray16le\fR is supported.
.SS
\fBinterpolationstudy
This is an additional tool. Pixel column interpolation study on \fIrgb48le\fR.
.SS
\fBframecropper
This is an additional tool. Crop center part of RGB frames.
.SH COPYRIGHT
Copyright (c) 2012 Joakim Reuteler
.LP
Copyright (c) 2018 AMIA Open Source
.SH LICENSE
The program is released under a GNU General Public License version 3 and the documentation is released under a Creative Commons Attribution 4.0 International License.
.SH DISCLAIMER
The lenticular package is provided "as is" without warranty or support of any kind.
